# Generated by Django 5.2.7 on 2025-10-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='observacoes',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
