# Generated by Django 5.2.7 on 2025-10-29 22:03

import System.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_veiculos_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Senha', models.CharField(max_length=255)),
                ('Telefone', models.CharField(max_length=20, unique=True)),
                ('Cargo', models.CharField(choices=[('mecanico', 'Mecânico'), ('motorista', 'Motorista'), ('administrador', 'Administrador')], max_length=14)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='manutencao',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='placa',
            field=models.CharField(max_length=7, unique=True, validators=[System.models.validar_placa]),
        ),
        migrations.AlterModelTable(
            name='veiculos',
            table='Veiculos',
        ),
        migrations.CreateModel(
            name='agendamento_fix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_prevista_manutencao', models.DateField()),
                ('Tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=11)),
                ('Motivo', models.CharField(max_length=255)),
                ('observacoes', models.TextField()),
                ('Veiculo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='System.veiculos')),
                ('Mecanico_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_como_mecanico', to='System.usuarios')),
                ('Motorista_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_como_motorista', to='System.usuarios')),
            ],
            options={
                'db_table': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('ativo', 'Ativo'), ('resolvido', 'Resolvido')], max_length=10)),
                ('Mensagem', models.TextField()),
                ('Veiculo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_do_veiculo', to='System.veiculos')),
            ],
            options={
                'db_table': 'Alerta',
            },
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_RealizacaoManu', models.DateField()),
                ('Tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva')], max_length=11)),
                ('Motivo', models.CharField(max_length=255)),
                ('Observacoes', models.TextField()),
                ('Custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Agendamento_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamento_fix', to='System.agendamento_fix')),
                ('Veiculo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_consertado', to='System.veiculos')),
                ('Mecanico_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_como_mecanico', to='System.usuarios')),
                ('Motorista_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_como_motorista', to='System.usuarios')),
            ],
            options={
                'db_table': 'Manutencoes',
            },
        ),
    ]
