# Generated by Django 5.2.7 on 2025-10-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0003_usuarios_remove_veiculos_manutencao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento_fix',
            old_name='observacoes',
            new_name='Observacoes',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='marca',
            new_name='Marca',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='modelo',
            new_name='Modelo',
        ),
        migrations.RenameField(
            model_name='veiculos',
            old_name='placa',
            new_name='Placa',
        ),
        migrations.AddField(
            model_name='manutencoes',
            name='Km_Manutencao',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manutencoes',
            name='Km_Proxima_Revisao',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='Km_Atual',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='registro_km',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Km_Leitura', models.BigIntegerField()),
                ('Data_Hora_Registro', models.DateTimeField(auto_now_add=True)),
                ('Fonte_Registro', models.CharField(choices=[('abastecimento', 'Abastecimento'), ('inicio_turno', 'Início de Turno'), ('mecanico', 'Mecânico (Check-in)')], max_length=15)),
                ('Motorista_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='System.usuarios')),
                ('Veiculo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_km', to='System.veiculos')),
            ],
            options={
                'db_table': 'RegistrosKM',
            },
        ),
    ]
